CREATE TABLE IF NOT EXISTS `STAR_CATALOG` (
`ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
`NAME` VARCHAR(250) DEFAULT NULL,
`RIGHT_ASCENSION` DOUBLE(10, 6),
`DECLINATION` DOUBLE(10, 6),
`RAD_RIGHT_ASCENSION` DOUBLE(19, 18),
`RAD_DECLINATION` DOUBLE(19, 18),
`MAGNITUDE` DOUBLE(10, 7),
`ABS_MAGNITUDE` DOUBLE(10, 2),
`X` DOUBLE(10, 6),
`Y` DOUBLE(10, 6),
`Z` DOUBLE(10, 6),
PRIMARY KEY (`ID`),
INDEX epoch (RIGHT_ASCENSION, DECLINATION)
)ENGINE=InnoDB DEFAULT CHARSET=utf8